### ISSUE TITLE
the version 4.x has es11 code after build in dist

### ISSUE THREAD

**Issue by xiyangzuile1995** [scttcper/tinycolor#247]
my project can't run after update @ctrl/tinycolor to 4.x!!!
![image](https://github.com/scttcper/tinycolor/assets/117340604/d681c75c-db0c-4b5a-be5a-fe956fbe6844)

**Comment by scttcper** [comment]
node 14 is required

**Comment by nanianlisao** [comment]
@scttcper I really hope you can be compatible. Because I mainly work on the browser.
 Judging from the mdn data, ?? syntax compatibility needs to reach chrome 80 to be supported, which is really hard for me to accept.
 For compatibility, I may need to do additional compilation, otherwise I can only choose to fall back to version 3.6.1.
 
At the same time, judging from the download data of npm, the download volume of 3.6.1 is far ahead.
